export type Country = {
	key: string;
	name: string;
	aliases?: readonly string[];
};

export const COUNTRIES = [
	{ key: "iceland", name: "アイスランド", aliases: ["Iceland"] },
	{ key: "ireland", name: "アイルランド", aliases: ["Ireland"] },
	{ key: "azerbaijan", name: "アゼルバイジャン", aliases: ["Azerbaijan"] },
	{ key: "afghanistan", name: "アフガニスタン", aliases: ["Afghanistan"] },
	{
		key: "united-states",
		name: "アメリカ合衆国",
		aliases: ["アメリカ", "米国", "United States"]
	},
	{
		key: "uae",
		name: "アラブ首長国連邦",
		aliases: ["UAE", "United Arab Emirates"]
	},
	{ key: "algeria", name: "アルジェリア", aliases: ["Algeria"] },
	{ key: "argentina", name: "アルゼンチン", aliases: ["Argentina"] },
	{ key: "aruba", name: "アルバ", aliases: ["Aruba"] },
	{ key: "albania", name: "アルバニア", aliases: ["Albania"] },
	{ key: "armenia", name: "アルメニア", aliases: ["Armenia"] },
	{ key: "anguilla", name: "アンギラ", aliases: ["Anguilla"] },
	{ key: "angola", name: "アンゴラ", aliases: ["Angola"] },
	{
		key: "antigua-and-barbuda",
		name: "アンティグア・バーブーダ",
		aliases: ["Antigua and Barbuda"]
	},
	{ key: "andorra", name: "アンドラ", aliases: ["Andorra"] },
	{ key: "yemen", name: "イエメン", aliases: ["Yemen"] },
	{
		key: "united-kingdom",
		name: "イギリス",
		aliases: ["英国", "United Kingdom", "UK"]
	},
	{ key: "israel", name: "イスラエル", aliases: ["Israel"] },
	{ key: "italy", name: "イタリア", aliases: ["Italy"] },
	{ key: "iraq", name: "イラク", aliases: ["Iraq"] },
	{ key: "iran", name: "イラン", aliases: ["Iran"] },
	{ key: "india", name: "インド", aliases: ["India"] },
	{ key: "indonesia", name: "インドネシア", aliases: ["Indonesia"] },
	{ key: "uganda", name: "ウガンダ", aliases: ["Uganda"] },
	{ key: "ukraine", name: "ウクライナ", aliases: ["Ukraine"] },
	{ key: "uzbekistan", name: "ウズベキスタン", aliases: ["Uzbekistan"] },
	{ key: "uruguay", name: "ウルグアイ", aliases: ["Uruguay"] },
	{ key: "ecuador", name: "エクアドル", aliases: ["Ecuador"] },
	{ key: "egypt", name: "エジプト", aliases: ["Egypt"] },
	{ key: "estonia", name: "エストニア", aliases: ["Estonia"] },
	{ key: "eswatini", name: "エスワティニ", aliases: ["Eswatini"] },
	{ key: "ethiopia", name: "エチオピア", aliases: ["Ethiopia"] },
	{ key: "eritrea", name: "エリトリア", aliases: ["Eritrea"] },
	{ key: "el-salvador", name: "エルサルバドル", aliases: ["El Salvador"] },
	{ key: "australia", name: "オーストラリア", aliases: ["Australia"] },
	{ key: "austria", name: "オーストリア", aliases: ["Austria"] },
	{ key: "oman", name: "オマーン", aliases: ["Oman"] },
	{ key: "netherlands", name: "オランダ", aliases: ["Netherlands"] },
	{ key: "ghana", name: "ガーナ", aliases: ["Ghana"] },
	{ key: "cape-verde", name: "カーボベルデ", aliases: ["Cape Verde"] },
	{ key: "guyana", name: "ガイアナ", aliases: ["Guyana"] },
	{ key: "kazakhstan", name: "カザフスタン", aliases: ["Kazakhstan"] },
	{ key: "qatar", name: "カタール", aliases: ["Qatar"] },
	{ key: "canada", name: "カナダ", aliases: ["Canada"] },
	{ key: "gabon", name: "ガボン", aliases: ["Gabon"] },
	{ key: "cameroon", name: "カメルーン", aliases: ["Cameroon"] },
	{ key: "gambia", name: "ガンビア", aliases: ["Gambia"] },
	{ key: "cambodia", name: "カンボジア", aliases: ["Cambodia"] },
	{ key: "guinea", name: "ギニア", aliases: ["Guinea"] },
	{ key: "guinea-bissau", name: "ギニアビサウ", aliases: ["Guinea-Bissau"] },
	{ key: "cyprus", name: "キプロス", aliases: ["Cyprus"] },
	{ key: "cuba", name: "キューバ", aliases: ["Cuba"] },
	{ key: "greece", name: "ギリシャ", aliases: ["Greece"] },
	{ key: "kiribati", name: "キリバス", aliases: ["Kiribati"] },
	{ key: "kyrgyzstan", name: "キルギス", aliases: ["Kyrgyzstan"] },
	{ key: "guatemala", name: "グアテマラ", aliases: ["Guatemala"] },
	{ key: "kuwait", name: "クウェート", aliases: ["Kuwait"] },
	{ key: "cook-islands", name: "クック諸島", aliases: ["Cook Islands"] },
	{ key: "grenada", name: "グレナダ", aliases: ["Grenada"] },
	{ key: "croatia", name: "クロアチア", aliases: ["Croatia"] },
	{ key: "kenya", name: "ケニア", aliases: ["Kenya"] },
	{ key: "cote-divoire", name: "コートジボワール", aliases: ["Cote d'Ivoire"] },
	{ key: "costa-rica", name: "コスタリカ", aliases: ["Costa Rica"] },
	{ key: "comoros", name: "コモロ", aliases: ["Comoros"] },
	{ key: "colombia", name: "コロンビア", aliases: ["Colombia"] },
	{
		key: "republic-of-the-congo",
		name: "コンゴ共和国",
		aliases: ["Republic of the Congo"]
	},
	{
		key: "democratic-republic-of-the-congo",
		name: "コンゴ民主共和国",
		aliases: ["Democratic Republic of the Congo"]
	},
	{ key: "saudi-arabia", name: "サウジアラビア", aliases: ["Saudi Arabia"] },
	{ key: "samoa", name: "サモア", aliases: ["Samoa"] },
	{
		key: "sao-tome-and-principe",
		name: "サントメ・プリンシペ",
		aliases: ["Sao Tome and Principe"]
	},
	{ key: "zambia", name: "ザンビア", aliases: ["Zambia"] },
	{ key: "san-marino", name: "サンマリノ", aliases: ["San Marino"] },
	{ key: "sierra-leone", name: "シエラレオネ", aliases: ["Sierra Leone"] },
	{ key: "djibouti", name: "ジブチ", aliases: ["Djibouti"] },
	{ key: "jamaica", name: "ジャマイカ", aliases: ["Jamaica"] },
	{ key: "georgia", name: "ジョージア", aliases: ["Georgia"] },
	{ key: "syria", name: "シリア", aliases: ["Syria"] },
	{ key: "singapore", name: "シンガポール", aliases: ["Singapore"] },
	{ key: "zimbabwe", name: "ジンバブエ", aliases: ["Zimbabwe"] },
	{ key: "switzerland", name: "スイス", aliases: ["Switzerland"] },
	{ key: "sweden", name: "スウェーデン", aliases: ["Sweden"] },
	{ key: "sudan", name: "スーダン", aliases: ["Sudan"] },
	{ key: "spain", name: "スペイン", aliases: ["Spain"] },
	{ key: "suriname", name: "スリナム", aliases: ["Suriname"] },
	{ key: "sri-lanka", name: "スリランカ", aliases: ["Sri Lanka"] },
	{ key: "slovakia", name: "スロバキア", aliases: ["Slovakia"] },
	{ key: "slovenia", name: "スロベニア", aliases: ["Slovenia"] },
	{ key: "seychelles", name: "セーシェル", aliases: ["Seychelles"] },
	{ key: "senegal", name: "セネガル", aliases: ["Senegal"] },
	{ key: "serbia", name: "セルビア", aliases: ["Serbia"] },
	{
		key: "saint-kitts-and-nevis",
		name: "セントクリストファー・ネービス",
		aliases: ["Saint Kitts and Nevis"]
	},
	{
		key: "saint-vincent-and-the-grenadines",
		name: "セントビンセント及びグレナディーン諸島",
		aliases: ["Saint Vincent and the Grenadines"]
	},
	{ key: "saint-lucia", name: "セントルシア", aliases: ["Saint Lucia"] },
	{ key: "somalia", name: "ソマリア", aliases: ["Somalia"] },
	{
		key: "solomon-islands",
		name: "ソロモン諸島",
		aliases: ["Solomon Islands"]
	},
	{ key: "thailand", name: "タイ", aliases: ["Thailand"] },
	{
		key: "south-korea",
		name: "大韓民国",
		aliases: ["韓国", "Korea", "South Korea"]
	},
	{ key: "tajikistan", name: "タジキスタン", aliases: ["Tajikistan"] },
	{ key: "tanzania", name: "タンザニア", aliases: ["Tanzania"] },
	{ key: "czechia", name: "チェコ", aliases: ["Czechia"] },
	{ key: "chad", name: "チャド", aliases: ["Chad"] },
	{
		key: "central-african-republic",
		name: "中央アフリカ",
		aliases: ["Central African Republic"]
	},
	{ key: "china", name: "中華人民共和国", aliases: ["中国", "China"] },
	{ key: "tunisia", name: "チュニジア", aliases: ["Tunisia"] },
	{ key: "chile", name: "チリ", aliases: ["Chile"] },
	{ key: "tuvalu", name: "ツバル", aliases: ["Tuvalu"] },
	{ key: "denmark", name: "デンマーク", aliases: ["Denmark"] },
	{ key: "germany", name: "ドイツ", aliases: ["Germany"] },
	{ key: "togo", name: "トーゴ", aliases: ["Togo"] },
	{
		key: "dominican-republic",
		name: "ドミニカ共和国",
		aliases: ["Dominican Republic"]
	},
	{ key: "dominica", name: "ドミニカ国", aliases: ["Dominica"] },
	{
		key: "trinidad-and-tobago",
		name: "トリニダード・トバゴ",
		aliases: ["Trinidad and Tobago"]
	},
	{ key: "turkmenistan", name: "トルクメニスタン", aliases: ["Turkmenistan"] },
	{ key: "turkey", name: "トルコ", aliases: ["Turkey"] },
	{ key: "tonga", name: "トンガ", aliases: ["Tonga"] },
	{ key: "nigeria", name: "ナイジェリア", aliases: ["Nigeria"] },
	{ key: "nauru", name: "ナウル", aliases: ["Nauru"] },
	{ key: "namibia", name: "ナミビア", aliases: ["Namibia"] },
	{ key: "niue", name: "ニウエ", aliases: ["Niue"] },
	{ key: "nicaragua", name: "ニカラグア", aliases: ["Nicaragua"] },
	{ key: "niger", name: "ニジェール", aliases: ["Niger"] },
	{ key: "japan", name: "日本", aliases: ["Japan"] },
	{ key: "new-zealand", name: "ニュージーランド", aliases: ["New Zealand"] },
	{ key: "nepal", name: "ネパール", aliases: ["Nepal"] },
	{ key: "norway", name: "ノルウェー", aliases: ["Norway"] },
	{ key: "bahrain", name: "バーレーン", aliases: ["Bahrain"] },
	{ key: "haiti", name: "ハイチ", aliases: ["Haiti"] },
	{ key: "pakistan", name: "パキスタン", aliases: ["Pakistan"] },
	{ key: "vatican-city", name: "バチカン", aliases: ["Vatican City"] },
	{ key: "panama", name: "パナマ", aliases: ["Panama"] },
	{ key: "vanuatu", name: "バヌアツ", aliases: ["Vanuatu"] },
	{ key: "bahamas", name: "バハマ", aliases: ["Bahamas"] },
	{
		key: "papua-new-guinea",
		name: "パプアニューギニア",
		aliases: ["Papua New Guinea"]
	},
	{ key: "palau", name: "パラオ", aliases: ["Palau"] },
	{ key: "paraguay", name: "パラグアイ", aliases: ["Paraguay"] },
	{ key: "barbados", name: "バルバドス", aliases: ["Barbados"] },
	{ key: "palestine", name: "パレスチナ", aliases: ["Palestine"] },
	{ key: "hungary", name: "ハンガリー", aliases: ["Hungary"] },
	{ key: "bangladesh", name: "バングラデシュ", aliases: ["Bangladesh"] },
	{ key: "timor-leste", name: "東ティモール", aliases: ["Timor-Leste"] },
	{ key: "fiji", name: "フィジー", aliases: ["Fiji"] },
	{ key: "philippines", name: "フィリピン", aliases: ["Philippines"] },
	{ key: "finland", name: "フィンランド", aliases: ["Finland"] },
	{ key: "bhutan", name: "ブータン", aliases: ["Bhutan"] },
	{ key: "brazil", name: "ブラジル", aliases: ["Brazil"] },
	{ key: "france", name: "フランス", aliases: ["France"] },
	{ key: "bulgaria", name: "ブルガリア", aliases: ["Bulgaria"] },
	{ key: "burkina-faso", name: "ブルキナファソ", aliases: ["Burkina Faso"] },
	{ key: "brunei", name: "ブルネイ", aliases: ["Brunei"] },
	{ key: "burundi", name: "ブルンジ", aliases: ["Burundi"] },
	{ key: "vietnam", name: "ベトナム", aliases: ["Vietnam"] },
	{ key: "benin", name: "ベナン", aliases: ["Benin"] },
	{ key: "venezuela", name: "ベネズエラ", aliases: ["Venezuela"] },
	{ key: "belarus", name: "ベラルーシ", aliases: ["Belarus"] },
	{ key: "belize", name: "ベリーズ", aliases: ["Belize"] },
	{ key: "peru", name: "ペルー", aliases: ["Peru"] },
	{ key: "belgium", name: "ベルギー", aliases: ["Belgium"] },
	{ key: "poland", name: "ポーランド", aliases: ["Poland"] },
	{
		key: "bosnia-and-herzegovina",
		name: "ボスニア・ヘルツェゴビナ",
		aliases: ["Bosnia and Herzegovina"]
	},
	{ key: "botswana", name: "ボツワナ", aliases: ["Botswana"] },
	{ key: "bolivia", name: "ボリビア", aliases: ["Bolivia"] },
	{ key: "portugal", name: "ポルトガル", aliases: ["Portugal"] },
	{ key: "honduras", name: "ホンジュラス", aliases: ["Honduras"] },
	{
		key: "marshall-islands",
		name: "マーシャル諸島",
		aliases: ["Marshall Islands"]
	},
	{ key: "madagascar", name: "マダガスカル", aliases: ["Madagascar"] },
	{ key: "malawi", name: "マラウイ", aliases: ["Malawi"] },
	{ key: "mali", name: "マリ", aliases: ["Mali"] },
	{ key: "malta", name: "マルタ", aliases: ["Malta"] },
	{ key: "malaysia", name: "マレーシア", aliases: ["Malaysia"] },
	{ key: "micronesia", name: "ミクロネシア", aliases: ["Micronesia"] },
	{ key: "south-africa", name: "南アフリカ", aliases: ["South Africa"] },
	{ key: "south-sudan", name: "南スーダン", aliases: ["South Sudan"] },
	{ key: "myanmar", name: "ミャンマー", aliases: ["Myanmar"] },
	{ key: "mexico", name: "メキシコ", aliases: ["Mexico"] },
	{ key: "mauritius", name: "モーリシャス", aliases: ["Mauritius"] },
	{ key: "mauritania", name: "モーリタニア", aliases: ["Mauritania"] },
	{ key: "mozambique", name: "モザンビーク", aliases: ["Mozambique"] },
	{ key: "monaco", name: "モナコ", aliases: ["Monaco"] },
	{ key: "maldives", name: "モルディブ", aliases: ["Maldives"] },
	{ key: "moldova", name: "モルドバ", aliases: ["Moldova"] },
	{ key: "morocco", name: "モロッコ", aliases: ["Morocco"] },
	{ key: "mongolia", name: "モンゴル", aliases: ["Mongolia"] },
	{ key: "montenegro", name: "モンテネグロ", aliases: ["Montenegro"] },
	{ key: "jordan", name: "ヨルダン", aliases: ["Jordan"] },
	{ key: "laos", name: "ラオス", aliases: ["Laos"] },
	{ key: "latvia", name: "ラトビア", aliases: ["Latvia"] },
	{ key: "lithuania", name: "リトアニア", aliases: ["Lithuania"] },
	{ key: "libya", name: "リビア", aliases: ["Libya"] },
	{
		key: "liechtenstein",
		name: "リヒテンシュタイン",
		aliases: ["Liechtenstein"]
	},
	{ key: "liberia", name: "リベリア", aliases: ["Liberia"] },
	{ key: "romania", name: "ルーマニア", aliases: ["Romania"] },
	{ key: "luxembourg", name: "ルクセンブルク", aliases: ["Luxembourg"] },
	{ key: "rwanda", name: "ルワンダ", aliases: ["Rwanda"] },
	{ key: "lesotho", name: "レソト", aliases: ["Lesotho"] },
	{ key: "lebanon", name: "レバノン", aliases: ["Lebanon"] },
	{ key: "russia", name: "ロシア", aliases: ["Russia"] },
	{
		key: "north-macedonia",
		name: "北マケドニア",
		aliases: ["North Macedonia"]
	},
	{ key: "north-korea", name: "北朝鮮", aliases: ["North Korea"] },
	{
		key: "equatorial-guinea",
		name: "赤道ギニア",
		aliases: ["Equatorial Guinea"]
	}
] as const satisfies readonly Country[];

function phoneCodes(...codes: string[]) {
	return codes.flatMap((code) => [code, `+${code}`]);
}

const PHONE_CODE_ALIASES = {
	iceland: phoneCodes("354"),
	ireland: phoneCodes("353"),
	azerbaijan: phoneCodes("994"),
	afghanistan: phoneCodes("93"),
	"united-states": phoneCodes("1"),
	uae: phoneCodes("971"),
	algeria: phoneCodes("213"),
	argentina: phoneCodes("54"),
	aruba: phoneCodes("297"),
	albania: phoneCodes("355"),
	armenia: phoneCodes("374"),
	anguilla: phoneCodes("1264"),
	angola: phoneCodes("244"),
	"antigua-and-barbuda": phoneCodes("1268"),
	andorra: phoneCodes("376"),
	yemen: phoneCodes("967"),
	"united-kingdom": phoneCodes("44"),
	israel: phoneCodes("972"),
	italy: phoneCodes("39"),
	iraq: phoneCodes("964"),
	iran: phoneCodes("98"),
	india: phoneCodes("91"),
	indonesia: phoneCodes("62"),
	uganda: phoneCodes("256"),
	ukraine: phoneCodes("380"),
	uzbekistan: phoneCodes("998"),
	uruguay: phoneCodes("598"),
	ecuador: phoneCodes("593"),
	egypt: phoneCodes("20"),
	estonia: phoneCodes("372"),
	eswatini: phoneCodes("268"),
	ethiopia: phoneCodes("251"),
	eritrea: phoneCodes("291"),
	"el-salvador": phoneCodes("503"),
	australia: phoneCodes("61"),
	austria: phoneCodes("43"),
	oman: phoneCodes("968"),
	netherlands: phoneCodes("31"),
	ghana: phoneCodes("233"),
	"cape-verde": phoneCodes("238"),
	guyana: phoneCodes("592"),
	kazakhstan: phoneCodes("7"),
	qatar: phoneCodes("974"),
	canada: phoneCodes("1"),
	gabon: phoneCodes("241"),
	cameroon: phoneCodes("237"),
	gambia: phoneCodes("220"),
	cambodia: phoneCodes("855"),
	guinea: phoneCodes("224"),
	"guinea-bissau": phoneCodes("245"),
	cyprus: phoneCodes("357"),
	cuba: phoneCodes("53"),
	greece: phoneCodes("30"),
	kiribati: phoneCodes("686"),
	kyrgyzstan: phoneCodes("996"),
	guatemala: phoneCodes("502"),
	kuwait: phoneCodes("965"),
	"cook-islands": phoneCodes("682"),
	grenada: phoneCodes("1473"),
	croatia: phoneCodes("385"),
	kenya: phoneCodes("254"),
	"cote-divoire": phoneCodes("225"),
	"costa-rica": phoneCodes("506"),
	comoros: phoneCodes("269"),
	colombia: phoneCodes("57"),
	"republic-of-the-congo": phoneCodes("242"),
	"democratic-republic-of-the-congo": phoneCodes("243"),
	"saudi-arabia": phoneCodes("966"),
	samoa: phoneCodes("685"),
	"sao-tome-and-principe": phoneCodes("239"),
	zambia: phoneCodes("260"),
	"san-marino": phoneCodes("378"),
	"sierra-leone": phoneCodes("232"),
	djibouti: phoneCodes("253"),
	jamaica: phoneCodes("1876"),
	georgia: phoneCodes("995"),
	syria: phoneCodes("963"),
	singapore: phoneCodes("65"),
	zimbabwe: phoneCodes("263"),
	switzerland: phoneCodes("41"),
	sweden: phoneCodes("46"),
	sudan: phoneCodes("249"),
	spain: phoneCodes("34"),
	suriname: phoneCodes("597"),
	"sri-lanka": phoneCodes("94"),
	slovakia: phoneCodes("421"),
	slovenia: phoneCodes("386"),
	seychelles: phoneCodes("248"),
	senegal: phoneCodes("221"),
	serbia: phoneCodes("381"),
	"saint-kitts-and-nevis": phoneCodes("1869"),
	"saint-vincent-and-the-grenadines": phoneCodes("1784"),
	"saint-lucia": phoneCodes("1758"),
	somalia: phoneCodes("252"),
	"solomon-islands": phoneCodes("677"),
	thailand: phoneCodes("66"),
	"south-korea": phoneCodes("82"),
	tajikistan: phoneCodes("992"),
	tanzania: phoneCodes("255"),
	czechia: phoneCodes("420"),
	chad: phoneCodes("235"),
	"central-african-republic": phoneCodes("236"),
	china: phoneCodes("86"),
	tunisia: phoneCodes("216"),
	chile: phoneCodes("56"),
	tuvalu: phoneCodes("688"),
	denmark: phoneCodes("45"),
	germany: phoneCodes("49"),
	togo: phoneCodes("228"),
	"dominican-republic": phoneCodes("1809", "1829", "1849"),
	dominica: phoneCodes("1767"),
	"trinidad-and-tobago": phoneCodes("1868"),
	turkmenistan: phoneCodes("993"),
	turkey: phoneCodes("90"),
	tonga: phoneCodes("676"),
	nigeria: phoneCodes("234"),
	nauru: phoneCodes("674"),
	namibia: phoneCodes("264"),
	niue: phoneCodes("683"),
	nicaragua: phoneCodes("505"),
	niger: phoneCodes("227"),
	japan: phoneCodes("81"),
	"new-zealand": phoneCodes("64"),
	nepal: phoneCodes("977"),
	norway: phoneCodes("47"),
	bahrain: phoneCodes("973"),
	haiti: phoneCodes("509"),
	pakistan: phoneCodes("92"),
	"vatican-city": phoneCodes("379", "39"),
	panama: phoneCodes("507"),
	vanuatu: phoneCodes("678"),
	bahamas: phoneCodes("1242"),
	"papua-new-guinea": phoneCodes("675"),
	palau: phoneCodes("680"),
	paraguay: phoneCodes("595"),
	barbados: phoneCodes("1246"),
	palestine: phoneCodes("970"),
	hungary: phoneCodes("36"),
	bangladesh: phoneCodes("880"),
	"timor-leste": phoneCodes("670"),
	fiji: phoneCodes("679"),
	philippines: phoneCodes("63"),
	finland: phoneCodes("358"),
	bhutan: phoneCodes("975"),
	brazil: phoneCodes("55"),
	france: phoneCodes("33"),
	bulgaria: phoneCodes("359"),
	"burkina-faso": phoneCodes("226"),
	brunei: phoneCodes("673"),
	burundi: phoneCodes("257"),
	vietnam: phoneCodes("84"),
	benin: phoneCodes("229"),
	venezuela: phoneCodes("58"),
	belarus: phoneCodes("375"),
	belize: phoneCodes("501"),
	peru: phoneCodes("51"),
	belgium: phoneCodes("32"),
	poland: phoneCodes("48"),
	"bosnia-and-herzegovina": phoneCodes("387"),
	botswana: phoneCodes("267"),
	bolivia: phoneCodes("591"),
	portugal: phoneCodes("351"),
	honduras: phoneCodes("504"),
	"marshall-islands": phoneCodes("692"),
	madagascar: phoneCodes("261"),
	malawi: phoneCodes("265"),
	mali: phoneCodes("223"),
	malta: phoneCodes("356"),
	malaysia: phoneCodes("60"),
	micronesia: phoneCodes("691"),
	"south-africa": phoneCodes("27"),
	"south-sudan": phoneCodes("211"),
	myanmar: phoneCodes("95"),
	mexico: phoneCodes("52"),
	mauritius: phoneCodes("230"),
	mauritania: phoneCodes("222"),
	mozambique: phoneCodes("258"),
	monaco: phoneCodes("377"),
	maldives: phoneCodes("960"),
	moldova: phoneCodes("373"),
	morocco: phoneCodes("212"),
	mongolia: phoneCodes("976"),
	montenegro: phoneCodes("382"),
	jordan: phoneCodes("962"),
	laos: phoneCodes("856"),
	latvia: phoneCodes("371"),
	lithuania: phoneCodes("370"),
	libya: phoneCodes("218"),
	liechtenstein: phoneCodes("423"),
	liberia: phoneCodes("231"),
	romania: phoneCodes("40"),
	luxembourg: phoneCodes("352"),
	rwanda: phoneCodes("250"),
	lesotho: phoneCodes("266"),
	lebanon: phoneCodes("961"),
	russia: phoneCodes("7"),
	"north-macedonia": phoneCodes("389"),
	"north-korea": phoneCodes("850"),
	"equatorial-guinea": phoneCodes("240")
} as const satisfies Partial<
	Record<(typeof COUNTRIES)[number]["key"], string[]>
>;

export const COUNTRY_OPTIONS = COUNTRIES.map((country) => ({
	label: country.name,
	value: country.name,
	keywords: [
		...(country.aliases ?? []),
		...(PHONE_CODE_ALIASES[country.key] ?? [])
	]
}));
